global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mlops-model-metrics'
    static_configs:
      - targets: ['model-exporter:8001']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'mlops-api'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Assuming your ML API runs on port 8000
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
