apiVersion: 1

contact_points:
  - orgId: 1
    name: webhook_alerts
    receivers:
      - uid: webhook_alerts
        type: webhook
        settings:
          url: http://localhost:8080/webhook
          httpMethod: POST

policies:
  - orgId: 1
    receiver: webhook_alerts
    group_by: ['alertname']
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
