apiVersion: 1

groups:
  - name: ml_model_alerts
    orgId: 1
    folder: MLOps Alerts
    interval: 30s
    rules:
      - uid: model_accuracy_low
        title: Model Accuracy Below Threshold
        condition: accuracy_check
        data:
          - refId: accuracy_check
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: model_accuracy < 0.85
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Model accuracy has dropped below 85%. Current value: {{ $value }}"
          summary: "ML Model performance degraded"
        labels:
          severity: critical
          component: ml_model

      - uid: data_drift_detected
        title: Data Drift Detected
        condition: drift_check
        data:
          - refId: drift_check
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: drift_p_value < 0.05
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Data drift detected. P-value: {{ $value }}. Features may have shifted distribution."
          summary: "Significant data drift detected"
        labels:
          severity: warning
          component: data_quality

      - uid: api_response_slow
        title: API Response Time High
        condition: response_time_check
        data:
          - refId: response_time_check
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: rate(api_response_time_seconds_sum[5m]) / rate(api_response_time_seconds_count[5m]) > 1.0
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Alerting
        for: 3m
        annotations:
          description: "API average response time is {{ $value }}s, which exceeds 1.0s threshold"
          summary: "API performance degraded"
        labels:
          severity: warning
          component: api_performance

      - uid: system_cpu_high
        title: System CPU Usage High
        condition: cpu_check
        data:
          - refId: cpu_check
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: system_cpu_usage_percent > 80
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "System CPU usage is {{ $value }}%, exceeding 80% threshold"
          summary: "High system resource usage"
        labels:
          severity: warning
          component: system_resources

      - uid: model_predictions_stalled
        title: Model Predictions Stalled
        condition: predictions_check
        data:
          - refId: predictions_check
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: increase(model_predictions_total[10m]) == 0
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Alerting
        for: 10m
        annotations:
          description: "No new model predictions in the last 10 minutes. Service may be down."
          summary: "Model prediction service stalled"
        labels:
          severity: critical
          component: ml_model
